### ISSUE TITLE
Long Running Function Failed

### ISSUE THREAD

**Issue by MuhammetDilmac** [openfaas-incubator/of-watchdog#103]
I have a function execution time during 35-40 minutes. When i try to run on my machine its working successfully. But deploy to openfaas and run async its not completed end return 502 error on callback (Running 1337.917547 second).

My callback response;

First;
```
POST / HTTP/1.1
Host: mycallbak
User-Agent: Go-http-client/1.1
Content-Length: 0
Date: Sun, 19 Jul 2020 11:05:16 GMT
X-Call-Id: fde2158a-d128-4d12-987b-e462afe44b45
X-Duration-Seconds: 1335.231629
X-Function-Name: myfunction
X-Function-Status: 502
Accept-Encoding: gzip
Connection: close
X-Forwarded-For: XXX.XX.XXX.XX
```

Second;
```
POST / HTTP/1.1
Host: mycallback
User-Agent: Go-http-client/1.1
Content-Length: 201
Content-Type: text/plain; charset=utf-8
Date: Sun, 19 Jul 2020 11:05:18 GMT
X-Call-Id: fde2158a-d128-4d12-987b-e462afe44b45
X-Duration-Seconds: 1.175109
X-Function-Name: myfunction
X-Function-Status: 500
Accept-Encoding: gzip
Connection: close
X-Forwarded-For: XXX.XX.XXX.XX

error finding function myfunction.: Get http://faas-swarm:8080/system/function/myfunction?namespace=: dial tcp 10.0.0.7:8080: connect: connection refused
```

Docker service logs;
<img width="953" alt="resim" src="https://user-images.githubusercontent.com/6417144/87873452-5ed7d000-c9ca-11ea-9e95-0c8a85730988.png">

My configuration;

<img width="463" alt="resim" src="https://user-images.githubusercontent.com/6417144/87871479-3e534a00-c9b9-11ea-8b25-1969fd950ffc.png">

## Expected Behaviour
Function work must be completed and return

## Current Behaviour
Function killed before the end

## Possible Solution
I don't have any idea.

## Steps to Reproduce (for bugs)
1. Create function
2. Add sleep 2100 second
3. Add configuration timeouts;
```yaml
exec_timeout: 2h
write_timeout: 2h
read_timeout: 2h
```
3. Run function async
3. Function terminated

## Context
There are many links that I need to pull data. It takes about 30-35 minutes to pull data from these. I cannot pull the data due to this error.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
19.03.8

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi I'm sorry but we don't offer technical support through github. You'll need to register for Slack and talk to the community there. 

I'd also recommend you read the documentation and troubleshooting guides. We do have a tutorial on how to configure timeouts. 

Alex
