### ISSUE TITLE
Is of-watchdog ready to merge into OpenFaaS?

### ISSUE THREAD

**Issue by Liwink** [openfaas-incubator/of-watchdog#17]
Hi OpenFaas, thanks a lot for this amazing project.
May I ask whether you have any plan about when to merge of-watchdog into faas?

**Comment by alexellis** [comment]
Hi @Liwink,

of-watchdog is released separately from this repository, I would imagine the repo moving to the openfaas org from the incubator org but it is not necessarily going to be "merged".

I'm not sure if this answers your question.. what was it you wanted to know about of-watchdog specifically?

Alex
