### ISSUE TITLE
Error deploying node8-express template to raspberrypi

### ISSUE THREAD

**Issue by gaurangdave** [openfaas-incubator/of-watchdog#19]
I tried to create sample express app from : 

https://github.com/openfaas-incubator/node8-express-template

But I see the following error in logs after deployment.  I am new to docker/openfaas  so sincere apologies if this is due to some setup issue on my end.

```
faas-node-express.1.dp85hxbcd6i3@pi03    | Forking - node [index.js]
faas-node-express.1.dp85hxbcd6i3@pi03    | 2018/06/07 03:54:17 Started logging stderr from function.
faas-node-express.1.dp85hxbcd6i3@pi03    | 2018/06/07 03:54:17 Started logging stdout from function.
faas-node-express.1.dp85hxbcd6i3@pi03    | 2018/06/07 03:54:17 Error reading stdout: EOF
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):18.05.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Raspian Lite

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
You should only need to type in:

```
faas template store pull node8-express-armhf
faas-cli new --lang node8-express-armhf --prefix=alexellis2 alex-node-armhf
faas-cli up -f alex-node-armhf.yml
```

From there edit the handler.js to change the result you return depending on your needs and add any npm modules you want to consume too.

**Comment by alexellis** [comment]
I have no issues at all accessing my new function on an RPi:

```
Forking - node [index.js]
2019/01/13 09:41:10 Started logging stdout from function.
2019/01/13 09:41:10 Started logging stderr from function.
2019/01/13 09:41:10 OperationalMode: http
2019/01/13 09:41:10 Writing lock-file to: /tmp/.lock
2019/01/13 09:41:12 stdout: OpenFaaS Node.js listening on port: 3000

2019/01/13 09:41:20 GET / - 200 OK - ContentLength: 25
```

It seems like the template is still working as designed, so I would suggest you both join the Slack community and send a message there with your GitHub repo so the community can help you.

https://docs.openfaas.com/community
