### ISSUE TITLE
is there a way to configure redirects?

### ISSUE THREAD

**Issue by pyramation** [openfaas-incubator/of-watchdog#34]
When in HTTP mode, redirects seem to be proxied, not actually redirected

## Expected Behaviour

When I

1. create a server in http mode, and
2. send a redirect, for example, `res.redirect('http://google.com')`

I expect when I visit my cloud function in the browser to redirect to `google.com`

## Current Behaviour

1. I visit the cloud function in the browser
2. the URL doesn't change (e.g. `http://127.0.0.13112/function/myfunction`)
3. the content rendered looks like the content of `google.com` (but the URL bar doesn't show google)

From my intuition, it looks like a proxy is happening here. 

## Possible Solution

Is there a way to create a flag that says something like `redirects` or `allow_redirects` or?

## Steps to Reproduce (for bugs)

1. Create a server using http mode.
2. Create a redirect response in a handler.
3. Visit the cloud function in a browser.

## Context

Would be ideal to use cloud functions for things like OAuth or other web based services

## Your Environment

0.4.0/of-watchdog

**Comment by alexellis** [comment]
Example to reproduce the behaviour:

```js
"use strict"

module.exports = (event, context) => {
  context
    .headers({'Location': 'https://www.google.com/'})
    .status(307)    // Temporary
    .succeed('Page has moved.')
}
```

With the [Node template](https://github.com/openfaas-incubator/node8-express-template).

The Golang code in of-watchdog proxies up the Node HTTP process which tells it to redirect to i.e. google.com - so that's what the proxy does, it fetches the site Node is telling it to fetch.

That's why you're seeing this.

I'd be curious to see what happens if you try using a "stateless microservice" with OpenFaaS - i.e. your own Dockerfile + Node / Express server - https://www.openfaas.com/blog/stateless-microservices/

**Comment by alexellis** [comment]
We'd have to update the Golang proxying code to support this.

This is how I did it for the auth service in OpenFaaS Cloud - I needed the router to pass back the redirect instruction to the client’s browser. https://github.com/openfaas/openfaas-cloud/blob/3d3ed09707817b436751b279973d6f26191930a4/router/main.go#L34

cc @LucasRoesler

**Comment by pyramation** [comment]
I just added an example repo with a bare microservice (as @alexellis suggested) here https://github.com/pyramation/redirect-openfaas-example

<img width="243" alt="screen shot 2018-10-16 at 10 59 22 am" src="https://user-images.githubusercontent.com/545047/47036992-9c8f3100-d132-11e8-80b4-b362092c4b64.png">

Here are my results:

My first route (just a text response) is A-OK:

![screen shot 2018-10-16 at 10 57 09 am](https://user-images.githubusercontent.com/545047/47036899-62be2a80-d132-11e8-86fb-4c17dd5347eb.png)
![screen shot 2018-10-16 at 10 57 17 am](https://user-images.githubusercontent.com/545047/47036904-65b91b00-d132-11e8-874f-f7c4d1d68782.png)

The redirect route, seems to work in sinatra, but not the browser:

![screen shot 2018-10-16 at 10 59 15 am](https://user-images.githubusercontent.com/545047/47037013-a4e76c00-d132-11e8-9be9-2817efbe6e20.png)
![screen shot 2018-10-16 at 10 59 04 am](https://user-images.githubusercontent.com/545047/47037016-a87af300-d132-11e8-8e7e-f39913d019bc.png)

**Comment by alexellis** [comment]
Hi @pyramation thanks for your help with this 👍 

The feature/fix is release and generally available.

Alex
