### ISSUE TITLE
[HTTP] Handle forked process exit

### ISSUE THREAD

**Issue by stefanprodan** [openfaas-incubator/of-watchdog#4]
When the forked process exist, the watchdog could log the exit code and release the lock file to trigger a container restart.

## Expected Behaviour
If the function process exists, the watchdog should log the exit code/stdio and release the lock file.

## Current Behaviour
Currently the  watchdog only logs that it couldn't read the stdio.

**Comment by alexellis** [comment]
This does panic because stderr is disconnected and result in the container stopping. Does that serve the purpose?

**Comment by stefanprodan** [comment]
I think we can close this, the exit code is not that important.
