### ISSUE TITLE
Function terminates as soon as it starts when exec_timeout = "0s"

### ISSUE THREAD

**Issue by ryskiwt** [openfaas-incubator/of-watchdog#48]
Dear maintainers,

README says that execution timeout will be disabled if exec_timeout is set to 0.
> Exec timeout for process exec'd for each incoming request (in seconds). Disabled if set to 0.

However, when I set exec_timeout to 0, my function terminated as soon as it starts.

## Expected Behaviour
Function never terminates while it is running.

## Current Behaviour
Function terminates as soon as it starts.

docker swarm log says:

```sh
$ docker service log -f myfunction
Upstream HTTP request error: Post http://127.0.0.1:5000/: context deadline exceeded
Upstream HTTP killed due to exec_timeout: 0s
```

## Possible Solution
Maybe this line causes immediate timeout.
https://github.com/openfaas-incubator/of-watchdog/blob/bae373954932a07d89ab926457d237f03f6c60dc/executor/http_runner.go#L127

You should set timeout only when ExecTimeout is non-zero value.

```go
ctx := context.Background()
if f.ExecTimeout != 0 {
	var cancel context.CancelFunc
	ctx, cancel = context.WithTimeout(ctx, f.ExecTimeout)
	defer cancel()
}
```

## Steps to Reproduce (for bugs)
1. fetch this template https://github.com/openfaas-incubator/python-flask-template/tree/master/template/python3-flask
2. add `ENV exec_timeout="0s"` to Dockerfile
3. create new function from the template
4. build, push, deploy and invoke the function

## Your Environment
Docker version 18.09.1, build 4c52b90
Docker swarm
Linux (vagrant, vm.box = "bento/centos-7.4")

Thank you.

**Comment by alexellis** [comment]
Hi thanks for raising this issue and for your interest.

IMHO `f.ExecTimeout != 0` seems like a bad idea, we should use Golang durations.

I would suggest we add validation in the function that aborts the process if "0s" is set in the code.

Alex

**Comment by ryskiwt** [comment]
Hi, alexellis. Thank you for your reply.

Why should the function abort if "0s" is set?
README says timeout will be disabled if 0 is set.

> Exec timeout for process exec'd for each incoming request (in seconds). Disabled if set to 0.

Is README necessary to be fixed?

**Comment by alexellis** [comment]
The string says `0` not `0s`.

Alex

**Comment by MuhammetDilmac** [comment]
@alexellis i set to 0 but error message given to 0s
```yaml
functions:
  my-function:
    lang: ruby-http-json
    handler: ./my-function
    image: my-function:latest
    environment:
      exec_timeout: 0
```

and it's my error;
```
my-function.1.uy6lq9a36zho@openfaas    | 2020/07/18 19:25:21 Upstream HTTP request error: Post http://127.0.0.1:3000/: context canceled
my-function.1.uy6lq9a36zho@openfaas    | 2020/07/18 19:25:21 Upstream HTTP killed due to exec_timeout: 0s
```

**Comment by alexellis** [comment]
Why would you set the timeout to 0 seconds, it makes absolutely no sense?

**Comment by alexellis** [comment]
If you're trying to get an unlimited timeout, then you may be barking up the wrong tree, instead, set it as high as you dare - i.e. 10m or 2h

**Comment by alexellis** [comment]
/set title: Support question on unlimited timeouts
