### ISSUE TITLE
of-watchdog can't be auto scaled?

### ISSUE THREAD

**Issue by chennqqi** [openfaas-incubator/of-watchdog#70]
I  created a of-watchdog which using go-http template.
set `max_inflight: 5`
with 80 Concurrent request. this was still only one pod instance on k8s

**Comment by burtonr** [comment]
The `max_inflight` parameter is used to limit the maximum number of requests that can be handled at a time. 

For scaling, please reference the docs on [Auto-scaling](https://docs.openfaas.com/architecture/autoscaling/)

Also, perhaps working through the labs ([Lab 9 on auto-scaling](https://github.com/openfaas/workshop/blob/master/lab9.md)) would help.

**Comment by burtonr** [comment]
Derek close

**Comment by burtonr** [comment]
Derek close
