### ISSUE TITLE
Add a new `static` mode for serving static content

### ISSUE THREAD

**Issue by matipan** [openfaas-incubator/of-watchdog#74]
## Expected Behaviour

Template creators would specify a new mode called `static` that would allow them to serve static content that they specified over http.

## Current Behaviour

Users cannot use the watchdog for serving static content. They would have to create their own static server or use an existing solution like nginx.

## Possible Solution

We would have a new mode called `static` and a new variable called `publish`, publish would have the relative path to the directory that the user wants to serve.

Something that we could add in the future is analytics so that users can now which blog posts or page was the most visited.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

While creating a template for static sites I was not able to reuse the watchdog.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by matipan** [comment]
Derek assign: me

**Comment by alexellis** [comment]
I'm thinking `static_path` for the folder.
