### ISSUE TITLE
Healthcheck for `FROM scratch` images.

### ISSUE THREAD

**Issue by reitermarkus** [openfaas-incubator/of-watchdog#86]
Currently, we are able to run `fwatchdog` in a `FROM scratch` image, but we cannot run the default healthcheck since there is no `[`/`test` command to check for a file's existence as far as I can tell.

## Possible Solution

We could add a subcommand for `fwatchdog` which in turn performs the health check instead of relying on a `[`/`test` command being present , i.e.

```dockerfile
HEALTHCHECK --interval=2s CMD ["/fwatchdog", "healthcheck"]
```

**Comment by alexellis** [comment]
Sounds like a fair request. I believe @stefanprodan does similar for his podinfo example. 

https://github.com/stefanprodan/podinfo

This would need to be applied to both watchdogs for consistency.
